Add the message header for socket transport
rockers7414/xmusic pull request #25
Opened 2017-03-12 12:34 UTC by rockers7414

2017-03-12 14:44 UTC, cclien0725 requested changes
There are some suggestions for you. Please revised it. Thanks.

2017-03-12 14:44 UTC, cclien0725 commented on daemon/xmusic-cli.py
> +        header = pack("=BHB", 29, len(request), 29)
The `header` may use `MessageHeader` to create.

2017-03-12 14:44 UTC, cclien0725 commented on daemon/xmusic-cli.py
> +        length = unpack("=BHB", sock.recv(4))[1]
The `length` may use `MesageHeader` to get the data length.

2017-03-12 14:44 UTC, cclien0725 commented on daemon/xmusic-cli.py
> +            buf = sock.recv(min(1024, length - len(response)))
The value of `1024` may use a constant to unified management. ex. `RPCHandler. MAX_BUF_LENGTH`.

2017-03-12 14:46 UTC, rockers7414 commented
Sorry, I just don't mention that the CLI should be refactored by @KocaMio. ;)

2017-03-19 14:56 UTC, rockers7414 commented
Okay, I've already completed the CLI part. Below is the sample of the result. Please help to review.
```
➜  daemon git:(add-msg-header) ./xmusic-cli.py
API loading...
****************************************
Welcome to xmusic-cli.
****************************************
xmusic> get_artist --artist_name "Ed Sheeran"
{"method": "get_artist", "params": {"artist_name": "Ed Sheeran", "source": "db"}, "jsonrpc": "2.0", "id": "e2476551-66cd-48c7-a643-17f066bd961e"}
{
    "result": [
        {
            "provider_id": "8e9d7910-0376-4c2d-8a43-264ec58b35e9",
            "name": "Ed Sheeran",
            "artist_id": "20f4ed21-666a-45ff-b530-e0049854e2d6",
            "provider_res_id": "6eUKZXaKkcviH0Ku9w2n3V",
            "popularity": "100",
            "images": [
                {
                    "height": "160",
                    "image_id": "95b1a015-568e-4f30-aea0-75892c086e7a",
                    "path": "https://i.scdn.co/image/f39b705ba6b1070c77bce4e9c21dff5bac96f21c",
                    "width": "160"
                },
                {
                    "height": "320",
                    "image_id": "5675803f-a562-4ba4-bb1e-1c950b80e4e4",
                    "path": "https://i.scdn.co/image/e21f791b600f04f9dd8ad2b6d9b3304a82e048ca",
                    "width": "320"
                },
                {
                    "height": "640",
                    "image_id": "3905342b-d08e-4fba-9ba1-53038f6e2729",
                    "path": "https://i.scdn.co/image/f0370da3f52161b07a461b4be9a64d0adbfb498d",
                    "width": "640"
                }
            ],
            "genres": [
                {
                    "genre_id": "7088b0fd-8ff7-49bf-b374-08280afb4f93",
                    "name": "pop"
                }
            ]
        }
    ],
    "id": "e2476551-66cd-48c7-a643-17f066bd961e",
    "jsonrpc": "2.0"
}
xmusic>
```

2017-03-19 15:34 UTC, cclien0725 approved these changes
Looks great. Nice job!

2017-03-19 15:49 UTC, rockers7414 commented
Thanks, I'll merge the pull request tomorrow night if no one has any concern.

2017-03-20 11:50 UTC, merged