Server api
rockers7414/xmusic pull request #26
Opened 2017-03-14 06:55 UTC by AbnerLin

Please review and approve, thx.

2017-03-15 13:39 UTC, rockers7414 commented on daemon/database/artistrepo.py
> +    def get_artist(self, artist_name):
This function should be named `get_artist_by_name` since we may have other ways to get the artist, such as `source id`.

2017-03-15 13:50 UTC, rockers7414 requested changes
Please revise per request.

2017-03-15 13:50 UTC, rockers7414 commented on daemon/decorator/serialize.py
> +            entitys = func(*args, **kwargs)
The plural of entity is entities.

2017-03-15 13:50 UTC, rockers7414 commented on daemon/database/albumrepo.py
> +    def get_album(self, album_name):
This function should be named `get_album_by_name`.

2017-03-15 15:42 UTC, rockers7414 commented
Once your PR is merged, I'll cover @KocaMio to finish the client side.

2017-03-16 02:47 UTC, AbnerLin commented
What is PR?

2017-03-16 02:48 UTC, rockers7414 commented
PR stands for pull request.

2017-03-16 03:04 UTC, rockers7414 approved these changes
Looks good. I'll merge it tonight if no one has any concern.

2017-03-16 11:30 UTC, merged